version: '3.1'

services:
  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: 5544
      MYSQL_DATABASE: playlist
    ports:
      - 3306:3306

  mailhog:
    image: mailhog/mailhog
    container_name: playlist-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
